### PR TITLE
NHibernate Config Cache

### PR DESCRIPTION
**Pull request by djsmith**
Hi,

I saw the issue asking about the NH config cache (https://github.com/codai/Sharp-Lite/issues/4) and since I put together that code for the SA project I though I would set it up here. I added the caching code to the MyStore project as well as the template. Take a look and let me know if you have any questions.

Dan

### CODE REVIEW

**Comment by djsmith** [comment]
Oh yea, I had to disable assembly signing since I don't have the password for the SharpLite.pfx file.

**Comment by nazjunaid** [comment]
Thanks for implementing Issue #4 I'll give this a go.

**Comment by codai** [comment]
Thanks very much djsmith; I intend to pull this in on Thursday of this week.

**Comment by codai** [comment]
djsmith, thank you again for taking the time to lend a hand with this.  I have added the configuration caching to master.

**Pull request closed without merging**
