### PR TITLE
With nuget

### PR DESCRIPTION
**Pull request by SlyNet**
Example of using nuget for dependencies management. 
I can't build the sharp-lite project itself because of signing could you test build process together with all changes?

### CODE REVIEW

**Comment by codai** [comment]
SlyNet, I've pushed a number of changes to master.  If you'd like to test out your nuget changes, the pfx password is "SharpLite"

**Comment by SlyNet** [comment]
Merged and resolved some conflicts. I didn't touch CaTS project, its in active development right now as I understand. 

What was done is that all projects use Nuget with package restore process for managing external dependencies like nhibernate, stucture map, etc

**Comment by codai** [comment]
Terrific...I look forward to taking a closer look at this soon.  Thank you
for the update!

Billy McCafferty

On Fri, Mar 9, 2012 at 1:33 AM, Andrey Kozhyn <
reply@reply.github.com

**Comment by oishiimendesu** [comment]
Bug: EntityWithTypedId<>

my Model inherit from EntityWithTypedId<string> 
when I run mapping throw this message:
----> NHibernate.MappingException : Cannot extend unmapped class: SharpLite.Domain.EntityWithTypedId`1

**Pull request closed without merging**
